Adding releasing process guide
open-telemetry/opentelemetry-dotnet-contrib pull request #101
Opened 2021-03-23 14:53 UTC by srprash

2021-03-23 16:08 UTC, srprash commented
Will fix the linting issues shortly.

2021-04-20 16:48 UTC, srprash commented
@cijothomas Can you take a look?

2021-04-20 16:53 UTC, cijothomas commented on build/RELEASING.md
> +9. Go to the [**Releases**](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/releases)
Could you add putting changelog from the released component in the github release as well.
Also, this should be a final one, *not* draft :)

2021-04-20 16:54 UTC, cijothomas commented on build/RELEASING.md
> +1. Create and push git tag for the project and the version of the project
please add atleast one example, like
git tag -a 1.0.0-rc2 -m "1.0.0-rc2"
git push origin 1.0.0-rc2

2021-04-20 22:52 UTC, cijothomas commented on build/RELEASING.md
> +    You can find the project tag prefix in the workflow file for the project.
the source of truth should be the .csproj. example : https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Contrib.Instrumentation.Elasticsearch/OpenTelemetry.Contrib.Instrumentation.ElasticsearchClient.csproj#L6

2021-05-04 16:53 UTC, cijothomas commented on build/RELEASING.md
> +9. Go to the [**Releases**](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/releases)
Just realized we are missing a pre-step  - which is to update changelog to change "unreleased" to actual version and date of release. This must be a pre-step. (similar to the main repo)

2021-05-04 16:53 UTC, cijothomas requested changes
Thanks!

Tried the steps for MT and ES released.
Shared feedback about what needs changes from the above attempts.

2021-05-04 17:13 UTC, srprash commented
Nice! Thanks for the pointers. Will add those in the guide. :)

2021-05-10 19:54 UTC, cijothomas commented on build/RELEASING.md
> +the project being released. The Changelog at this point **must** include the
yes. (powershell or manual step)

2021-05-11 03:53 UTC, cijothomas commented on build/RELEASING.md
> +1. Update the Changelog for your project with relevant details. You
How about:
1. Decide on the version to be used.
2. Update changelog to replace Unreleased with this version and add date of release.
3. Submit PR to update changelog and get it merged.

and in the Steps.1 - mention that the version should be same as the one updated in changelog.

2021-05-11 23:23 UTC, merged