Rename package: OpenTelemetry.Contrib.Extensions.AWSXRay to OpenTelemetry.Extensions.AWS
open-telemetry/opentelemetry-dotnet-contrib pull request #1232
Opened 2023-06-09 14:00 UTC by rypdal

Name of the package OpenTelemetry.Contrib.Extensions.AWSXRay is not consistent with current naming conventions. 
1. Contrib suffix should be removed
2. AWSXRay should be replaced by AWS (see discussion https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/875#issuecomment-1452338635)

Package has been renamed to OpenTelemetry.Extensions.AWS. Namespaces, etc have been aligned accordingly.

2023-06-09 14:07 UTC, rypdal commented
@srprash, @atshaw43, @Kielek and @Oberon00: I would be very thankful for your review and comments. 
This PR is the pre-requisite for releasing of the new OpenTelemetry.Extensions.AWS package, which is used by OpenTelemetry.Contrib.Instrumentation.AWS and OpenTelemetry.Instrumentation.AWSLambda packages.

2023-06-12 09:08 UTC, Kielek approved these changes
I have pushed some minor changes directly to your branch.

LGTM.

2023-06-12 17:05 UTC, Oberon00 commented on .github/ISSUE_TEMPLATE/comp_contrib_extensions_aws.md
> +labels: comp:extensions.aws
If this is merge, don't forget to rename the label on GitHub as well.

2023-07-05 02:28 UTC, srprash approved these changes

2023-07-05 07:34 UTC, Oberon00 requested changes
Make sure not to merge, there is a mistake here: The goal was to remove the "Contrib" part from the name, but this renames AWSXray to AWS which would then ultimately lead to conflicts.

2023-07-05 07:42 UTC, Oberon00 commented
Or maybe it's not a mistake, I'm a bit confused now. I'm pretty sure we want to remove "contrib" but why do we want to remove "xray"? Will this then not be easy to confuse with the other "AWS" package (Extensions vs Instrumentation)?

2023-07-05 13:09 UTC, rypdal commented
@Oberon00:  I think renaming to OpenTelemetry.Extensions.AWS should be fine as it will no conflict with OpenTelemetry.Instrumentation.AWS. Also it more or less reflects what is this package for.

2023-07-27 10:39 UTC, merged