[repo] Prepare release Exporter.Geneva-1.9.0-rc.1
open-telemetry/opentelemetry-dotnet-contrib pull request #1875
Opened 2024-06-10 19:41 UTC by opentelemetrybot

Note: This PR was opened automatically by the [prepare release workflow](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/workflows/prepare-release.yml).

## Changes

* CHANGELOG files updated for projects being released.

2024-06-10 19:50 UTC, CodeBlanch commented on src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> +  ([#1834](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1869))
Has 1834 in the text but links to 1869

2024-06-10 19:52 UTC, vishweshbankwar commented on src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> +  ([#1834](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1869))
```suggestion
  ([#1869](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1869))
```

2024-06-10 19:52 UTC, vishweshbankwar commented on src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> +  ([#1834](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1869))
good catch. fixed.

2024-06-10 20:08 UTC, rajkumar-rangaraj approved these changes

2024-06-10 20:25 UTC, Kielek requested changes
I do not think that the changelogis true, see https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/6b604c4b2e030b91958a55da70d4dcc7842f496c/src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj#L18

Feel free to ignore blocking whe you fix/double checking

2024-06-10 23:15 UTC, vishweshbankwar commented
> I do not think that the changelogis true, see
> 
> https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/6b604c4b2e030b91958a55da70d4dcc7842f496c/src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj#L18
> 
> Feel free to ignore blocking when you fix/double checking

@Kielek - `OtelSdkVersion` actually points to `OpenTelemetryCoreLatestPrereleaseVersion`. See https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/6b604c4b2e030b91958a55da70d4dcc7842f496c/src/OpenTelemetry.Exporter.Geneva/Common.GenevaExporter.props#L3

Will be working on removing this indirect dependency.

2024-06-10 23:23 UTC, vishweshbankwar commented
I am going to hold on to this for now: would like to get the change added in Log Exporter to support https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/CHANGELOG.md#190-rc1. Will send a separate PR.

2024-06-11 10:01 UTC, Kielek approved these changes

2024-06-12 18:16 UTC, Kielek commented on src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> +## 1.9.0-rc.1
```suggestion
## Unreleased

## 1.9.0-rc.1
```

2024-06-12 18:38 UTC, merged

2024-06-12 19:01 UTC, CodeBlanch commented
Just FYI the automation didn't run when this was merged because after #1873 it looks for "[release]" in the PR title not "[repo]". I asked @vishweshbankwar to manually push the tag. Sorry @vishweshbankwar!