Create package-Exporter.Geneva.yml
open-telemetry/opentelemetry-dotnet-contrib pull request #304
Opened 2022-04-14 18:42 UTC by mic-max

Fixes #300

2022-04-14 19:02 UTC, cijothomas requested changes
See https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/304/files#r850725649

2022-04-14 21:12 UTC, cijothomas approved these changes

2022-04-14 23:11 UTC, cijothomas commented
@mic-max Please check and resolve the conflict.

2022-04-14 23:24 UTC, merged

2022-04-15 05:12 UTC, utpilla commented
@mic-max Update the .sln file as well