Use File scoped namespace statements
open-telemetry/opentelemetry-dotnet-contrib pull request #314
Opened 2022-04-18 21:27 UTC by mic-max

Fixes [#276](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/276)

To review please enable the ignore whitespace changes option

2022-04-18 21:30 UTC, reyang commented
That's a huge PR! 😄

2022-04-18 21:52 UTC, mic-max commented on src/OpenTelemetry.Instrumentation.Wcf/TelemetryServiceBehavior.cs
> +
What's this...

2022-04-18 22:29 UTC, reyang approved these changes
LGTM, it's a big PR and the actual change will probably make `git blame` experience much harder.

Personally, I don't have problem with `git blame`, it's just an extra 30 seconds digging into the history. Not sure if the code owners found it problematic.

2022-04-19 09:29 UTC, utpilla approved these changes

2022-04-22 05:46 UTC, cijothomas commented
@mic-max Has many conflicts.. could you resolve?

2022-04-24 15:02 UTC, cijothomas requested changes
Please submit smaller PRs. Its hard to look at 200+ files to make sure no accidental changes are made part of this PR. I get that the actual change is minimal, but need to ensure no accidental changes are part of this. I'd suggest to do at max ~25 files

2022-06-23 03:42 UTC, closed without merging