[Exporter.Geneva] Add support for UpDownCounter and ObservableUpDownCounter
open-telemetry/opentelemetry-dotnet-contrib pull request #685
Opened 2022-10-10 21:32 UTC by utpilla

## Changes
- Update the OTel SDK version used
- Add support for UpDownCounter and ObservableUpDownCounter

For significant contributions please make sure you have completed the following items:

* [ ] Appropriate `CHANGELOG.md` updated for non-trivial changes

2022-10-13 00:38 UTC, mic-max approved these changes

2022-10-13 04:52 UTC, Kielek approved these changes

2022-10-13 05:04 UTC, cijothomas commented on src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
> +                        case MetricType.LongSumNonMonotonic:
need to handle -ve values?

2022-10-13 05:04 UTC, cijothomas approved these changes
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/685/files#r994145083
Need to confirm how to deal with negative values.

2022-10-13 05:23 UTC, cijothomas requested changes
Approved by mistake. see previous comment.

2022-10-20 21:28 UTC, cijothomas commented on src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
> +                                // see: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/numeric-conversions#implicit-numeric-conversions
```suggestion
                                // see: https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/numeric-conversions#implicit-numeric-conversions
```

2022-10-20 21:31 UTC, cijothomas approved these changes

2022-10-20 22:10 UTC, merged